name: Windows

on:
  push:
    branches:
        - '*'
  pull_request:
    branches: [ master-dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
 
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1
  
    - name: Get latest CMake and ninja
      uses: lukka/get-cmake@latest

    - name: Build DynamicEngine
      run: |
    
        make -C build
